http_port 3128
cache_dir ufs ./squid/cache 100 16 256
cache_mem 256 MB
maximum_object_size 128 MB

visible_hostname localhost
pid_filename ./squid/squid.pid

acl allowed_domains dstdomain .circleci.com .github.com .githubusercontent.com .githubassets.com

http_access allow localhost
http_access allow allowed_domains
http_access deny all

access_log ./squid/logs/access.log
cache_log ./squid/logs/cache.log

cache_mgr admin@example.com

dns_nameservers 8.8.8.8 8.8.4.4

connect_timeout 30 seconds
read_timeout 5 minutes
request_timeout 5 minutes

via off
forwarded_for off 