http_port 3128 transparent

acl allowed_domains dstdomain .circleci.com .github.com .githubusercontent.com .githubassets.com

http_access allow allowed_domains
http_access deny all

access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log

debug_options ALL,1

cache_mem 0 