version: 2.1

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  job1:
    executor: custom-node
    steps:
      - run: echo "Running job 1"
      - run: |
          mkdir file
          echo "sent to job 2" >> file/cache.txt
      - save_cache:
          paths:
            - file/cache.txt
          key: cloud-cache-v1
  job2:
    executor: custom-node
    steps:
      - restore_cache:
          keys:
            - cloud-cache-v1
      - run: cat ./file/cache.txt

workflows:
  job-workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
