version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run:
          name: Fake conditional halt
          command: circleci step halt
      - setup_remote_docker:
          docker_layer_caching: true


workflows:
  workflow-a:
    jobs:
      - job_a