version: 2.1

jobs:
  convert-uuid-to-username:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
          curl --request GET \
          --url https://circleci.com/api/v2/me \
          --header 'Circle-Token: $CIRCLECI_TOKEN'

workflows:
  version: 2
  convert-via-api:
    jobs:
      - convert-uuid-to-username