version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    parameters:
      path: 
        type: string
        default: ~/project
      quiet:
        type: string
        default: --quiet
    steps:
      - checkout
      - run: |
              sudo apt update ; sudo apt install cloc
      - run: | 
              echo "$PATH" 
              echo "$QUIET"
      - run: |
              clc="${PATH} ${QUIET}"
              export CLOC_PARAMS=$clc" >> $BASH_ENV
              source $BASH_ENV
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^beta.*/