version: 2.1

parameters:
  environment:
    type: string
    default: "cypress/config/qa.config.json"

orbs:
  cypress: cypress-io/cypress@1.29.0


workflows:
  cypress-test:
    jobs:
      - cypress/install
      - cypress/run:
          config-file: << pipeline.parameters.environment >>
          requires: 
            - cypress/install
