version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run:
          name: Install pyyaml
          command: pip3 install pyyaml
      - run:
          name: Use pyyaml in python3 shell
          shell: python3
          command: |
            #!/usr/bin/env python3
            
            import yaml

            yaml.load("""
            ... - Hesperiidae
            ... - Papilionidae
            ... - Apatelodidae
            ... - Epiplemidae
            ... """)

workflows:
  workflow-a:
    jobs:
      - job_a