version: 2.1

# parameters:
#   first-matrix:
#     type: enum
#     enum: ["first", "second", "third"]
#     default: "first"
#   second-matrix:
#     type: enum
#     enum: ["un", "deux", "trois"]
#     default: "un"

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    parameters:
      version:
        type: string
      os:
        type: string
    executor: base
    steps:
      - checkout
      - run: echo "Running job a with matrix << parameters.version >>--<< parameters.os >>"
  job_b:
    parameters:
      version:
        type: string
      os:
        type: string
    executor: base
    steps:
      - checkout
      - run: echo "running job b with matrix << parameters.version >>--<< parameters.os >>"

workflows:
  workflow:
    jobs:
      - job_a:
          name: job-a-v-<< matrix.version >>-<< matrix.os >>
          matrix:
            parameters:
              version: ["first", "second", "third"]
              os: ["macOs", "windows", "linux"]
      - job_b:
          name: job-b-v-<< matrix.version >>
          matrix:
            parameters:
              version: ["first", "second", "third"]
              os: ["macOs", "windows", "linux"]
          requires:
            - job-a-v-<< matrix.version >>-<< matrix.os >>
