version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  setup_job:
    executor: custom-node
    steps:
      - continuation/continue:
          configuration_path: ./continue-config.yml



workflows:
  setup:
    jobs:
      - setup_job
