version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.0
  continuation: circleci/continuation@0.2.0

jobs:
  place_holder:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      run: echo hello john 

workflows:
  setup-workflow:
    jobs:
      - place_holder:
          filters:
            only:
              branches:
                - main
      - path-filtering/filter:
          name: check path
          mapping: |
            path_a/.* run-path-a true
            path_b/.* run-path-b true
          base-revision: main
          config-path: .circleci/continue-config.yml
          filters:
            tags:
              ignore: /.*/
          requires:
            - place_holder