version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  build-deploy:
    executor: base
    steps:
      - checkout
      - run: docker build -t nicks-testing .
      - run: aws sts assume-role-with-web-identity --role-arn "arn:aws:iam::660990364978:role/BasicEng" --role-session-name Nick-S-test --web-identity-token $CIRCLE_OIDC_TOKEN
      - run: docker tag nicks-testing:latest 660990364978.dkr.ecr.us-east-2.amazonaws.com/nicks-testing:latest
      - run: docker push 660990364978.dkr.ecr.us-east-2.amazonaws.com/nicks-testing:latest

workflows:
  job-workflow:
    jobs:
      - build-deploy
