version: 2.1

orbs:
  gh: circleci/github-cli@2.1.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - gh/setup
      - run: mkdir clone1 clone2
      - gh/clone:
          repo: felixshiftellecon/circleci-playground
          dir: clone1
      - gh/clone:
          repo: felixshiftellecon/cci-runner-demo
          dir: clone2

workflows:
  test:
    jobs:
      - job_a