version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  mac:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1
  docker:
    docker:
      - image: cimg/python:3.11.4


jobs:
  mac_job:
    executor: mac
    steps:
      - checkout
      - run:
          name: Install pyyaml
          command: pip3 install pyyaml
      - run:
          name: Use pyyaml in python3 shell
          shell: python3
          command: |
            #!/usr/bin/env python3
            
            import yaml

            yaml.safe_load("""
            ... - Hesperiidae
            ... - Papilionidae
            ... - Apatelodidae
            ... - Epiplemidae
            ... """)
  docker_job:
    executor: docker
    steps:
      - checkout
      - run:
          name: Install pyyaml
          command: pip3 install pyyaml
      - run:
          name: Use pyyaml in python3 shell
          shell: python3
          command: |
            #!/usr/bin/env python3
            
            import yaml

            yaml.safe_load("""
            ... - Hesperiidae
            ... - Papilionidae
            ... - Apatelodidae
            ... - Epiplemidae
            ... """)

workflows:
  workflow-a:
    jobs:
      - mac_job
      - docker_job