version: 2.1

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  job1:
    machine: true
    resource_class: felixshiftellecon/runner1
    steps:
      - run: echo "Running job 1 on runner"
  job2:
    executor: custom-node
    steps:
      - run: echo "running job 2"



workflows:
  job-workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
