version: 2.1

# parameters:
#   first-matrix:
#     type: enum
#     enum: ["first", "second", "third"]
#     default: "first"
#   second-matrix:
#     type: enum
#     enum: ["un", "deux", "trois"]
#     default: "un"

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a with version" << matrix.version >>
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b with version" << matrix.version >>

workflows:
  workflow:
    jobs:
      - job_a:
          name: job_a_v<< matrix.version >>
          matrix:
            parameters:
              version: ["first", "second", "third"]
      - job_b:
          name: job_b_v<< matrix.numberset >>
          matrix:
            parameters:
              version: ["un", "deux", "trois"]
          requires:
            - job_a_v<< matrix.version >>
