version: 2.1

orbs:
  orb-test: felixshiftellecon/orb-test@1.0.0

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  setup:
    executor: base
    steps:
      - run: echo "Running setup"
  job_1:
    executor: base
    parameters:
      env:
       type: string
       default: "dev"
    steps:
      - run: echo "Running job <<parameters.env>>"
  job_2:
    executor: base
    parameters:
      env:
       type: enum
       enum: ["dev", "test"]
    steps:
      - run: echo "running job b"
  job_3:
    executor: base
    parameters:
      env:
       type: enum
       enum: ["dev", "test"]
    steps:
      - run: echo "Running job <<parameters.env>>"

job_a: &job_a
  name: job_a
  requires:
    - setup

job_b: &job_b
  name: job_b
  requires:
    - job_a

job_c: &job_c
  name: job_c
  requires:
    - job_a

workflows:
  workflow:
    jobs:
      - setup
      - job_1:
          env: test
          name: job_a
          requires:
            - setup
      - job_2:
          env: test 
          name: job_b
          requires:
            - job_a
      - job_3:
          env: test
          requires:
            - job_a
  workflow-2:
    jobs:
      - setup
      - job_1:
          env: dev
          name: job_a
          requires:
            - setup
      - job_2:
          env: dev 
          name: job_b
          requires:
            - job_a
      - job_c:
          env: dev
          <<: *job_c 