version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
  job_b:
    executor: base
    parameters:
      env:
        type: string
        default: test
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

name-anchor: &name-anchor
  name: anchor-named

workflows:
  workflow:
    jobs:
      - job_a:
          name: non-anchor named
      - job_b: 
          env: dev
          <<: *name-anchor