version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
    working_directory: /path_a

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run:
          command: |
                    pwd
                    mkdir test_folder/
                    cd test_folder/
                    pwd
      - run: pwd

workflows:
  workflow-a:
    jobs:
      - job_a