version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: felixshiftellecon/container-runner-1

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

workflows:
  workflow-a:
    jobs:
      - job_a
      - job_b
