version: 2.1

orbs:
  sumologic: circleci/sumologic@1.3.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - sumologic/workflow-collector

workflows:
  workflow-a:
    jobs:
      - job_a