version: 2.1

executors:
  macgen1:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1
  macgen2:
    macos:
      xcode: "14.2.0"
    resource_class: macos.x86.medium.gen2
  oldxcode:
    macos:
      xcode: "14.0.1"
    resource_class: macos.m1.medium.gen1
  docker:
    docker:
      - image: cimg/python:3.11.4

commands:
  pyyaml:
    description: install pyyaml and use it
    steps:
      - run:
            name: Install pyyaml
            command: pip3 install pyyaml
      - run:
          name: Use pyyaml in python3 shell
          shell: python3
          command: |
            #!/usr/bin/env python3
            
            import yaml

            yaml.safe_load("""
            - Hesperiidae
            - Papilionidae
            - Apatelodidae
            - Epiplemidae
            """)

jobs:
  macgen1_job:
    executor: macgen1
    steps:
      - pyyaml
  macgen2_job:
    executor: macgen2
    steps:
      - pyyaml
  olderxcode_job:
    executor: oldxcode
    steps:
      - pyyaml
  docker_job:
    executor: docker
    steps:
      - pyyaml

workflows:
  workflow-a:
    jobs:
      - macgen1_job
      - macgen2_job
      - docker_job