version: 2.1
    
jobs:
  job_a:
    macos:
      xcode: "14.2.0"
      resource_class: macos.m1.large.gen1
    steps:
      - run: echo "Running job a"

workflows:
  workflow-a:
    jobs:
      - job_a