version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp
  machine-executor:
    machine: 
      image: ubuntu-2004:202107-02
    working_directory: /tmp

jobs:
  flow:
    executor: docker-executor
    steps:
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output

  downstream-machine:
    executor: machine-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  
  downstream-macOS:
    macos:
      xcode: 11.3.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  downstream-windows:
    executor: win/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
            if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
              echo "It worked!";
            else
              echo "Nope!"; exit 1
            fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream-machine:
          requires:
            - flow
      - downstream-macOS:
          requires:
            - flow
      - downstream-windows:
          requires:
            - flow