version: 2.1

setup: true

orbs:
  node: circleci/node@5.1.0

commands:
  node-install:
    steps:
      - node/install-packages:
            pkg-manager: yarn
            #Remove this if you want by branch caching
            include-branch-in-cache-key: false

jobs:
  testing:
      docker:
          - image: cimg/base:latest
      resource_class: small
      steps:
        - node-install

workflows:
  setup-workflow:
    jobs:
      - testing