version: 2.1

orbs:
  gh: circleci/github-cli@2.1.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - gh/setup
      - run: mkdir theclone
      - gh/clone:
          repo: felixshiftellecon/cci-runner-demo
          dir: theclone

workflows:
  test:
    jobs:
      - job_a