version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: circleci step halt

workflows:
  workflow-a:
    jobs:
      - job_a:
          pre-steps:
            - run:
              command: echo "I'm a pre step"
          post-steps:
            - run:
                command: echo "I'm a post step"