version: 2.1

orbs: 
  orb-test: felixshiftellecon/orb-test@1.0.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - orb-test/greet

workflows:
  job-workflow:
    jobs:
      - job_a
