version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    environment:
      CODEPUSH_DEPLOYMENT_NAME: $CIRCLE_PULL_REQUEST
    steps:
      - run: echo $CODEPUSH_DEPLOYMENT_NAME
      - run: echo $CIRCLE_PULL_REQUEST

workflows:
  workflow-a:
    jobs:
      - job_a