version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: |
              echo "export test='testing'" >> new_env_vars
              echo "export PR_number=${CIRCLE_PULL_REQUEST##*/}" >> new_env_vars
      - run: |
              cat new_env_vars >> "$BASH_ENV"
              source "$BASH_ENV"
              echo $PR_number

workflows:
  workflow-a:
    jobs:
      - job_a