version: 2.1

parameters:
  is-false:
    type: boolean
    default: false
    
    
jobs:
  job_a:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1
    steps:
      - run: echo "Running job a"

workflows:
  workflow-a:
    when: 
      and: << pipeline.parameters.is-false >>
    jobs:
      - job_a
