version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  upstream_workflow_triggerer:
    executor: base
    steps:
      - checkout
      - run: |
              echo "Here we run some conditional to check if a terraform deployment is needed"
              echo "This can be done by appending the commit with something like [deploy tf] and checking for it"
              echo "Or this can be done by adding a pipeline parameter to the trigger for this setup workflow"
              echo "then we put that into a setup_parameters.json file"
      - run: |
              echo "now that we checked for the terraform deploy, we can look at the tfvars file to see what environment needs to be used"
              echo "then we put that into the setup_parameters.json file"
              echo "it can be helpful to pass a parameter so we know when an environment is required for testing"
      - run: |
              echo "we can have a step that checks for a destroy parameter from the trigger and then run a destroy workflow"
              echo  "then we put that into the setup_parameters.json file"
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          # you'd pass the parameter file here
          parameters: { "infrastructure-required": "true", "destroy-infrastructure": "true", "testing-required": "true"}

workflows:
  setup-workflow:
    jobs:
      - upstream_workflow_triggerer