version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
  iterable-runner:
    docker:
      - image: 203113165317.dkr.ecr.us-east-1.amazonaws.com/circleci-runner
        aws_auth:
          oidc_role_arn: arn:aws:iam::203113165317:role/circleci-oidc
    resource_class: runners-namespace/selfhosted-runners-resource-class

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

workflows:
  workflow-a:
    jobs:
      - job_a
  workflow-b:
    jobs:
      - job_b