version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job:
    executor: base
    parameters:
        names:
          default: "john"
          type: string
    steps:
      - run: echo "I'm in <<parameters.names>>"

workflows:
  workflow-a:
    jobs:
      - job:
          matrix:
            parameters:
              names: ["john", "phil"]
          pre-steps:
            - run:
                command: echo "I'm from a pre step"