version: 2.1

orbs:
  python: circleci/python@2.2.0
  private-orb-test: felixshiftellecon/private-orb-test@1.0.1
  kustomize: finc/kustomize@0.0.2

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  cci_orb:
    executor: base
    steps:
      - python/install-packages:
          pkg-manager: pip
  private_orb:
    executor: base
    steps:
      - private-orb-test/greet
  uncertified_orb:
    executor: base
    steps:
      - kustomize/install

workflows:
  workflow-a:
    jobs:
      - cci_orb
      - private_orb
      - uncertified_orb
