version: 2.1

jobs:
  job_a:
    machine:
      image: ubuntu-2204:2024.05.1
    steps:
      - run:
          name: Start User Session
          environment:
            USER: "nick"
          command: |
            sudo loginctl enable-linger $USER
            dbus-launch --exit-with-session /bin/bash
      - run:
          name: Verify Session
          command: |
            echo "Current User: $(whoami)"
            echo "Active Sessions: $(who)"
workflows:
  workflow-a:
    jobs:
      - job_a