version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo << pipeline.id >>

workflows:
  workflow-a:
    jobs:
      - hold:
          type: approval
          pre-steps:
            - run: |
                sleep 15
                echo "Canceling workflow as too much time has elapsed"
                curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}"
              background: true
      - job_a:
          requires:
            - hold
      