version: 2.1
executors:
  go:
    docker:
    - image: cimg/go:1.17.3
jobs:
  job_a:
    steps:
    - run:
        command: checkout
    - run:
        command: echo Running job a
    - run:
        command: cat path_a/README.md
    executor: go
  job_b:
    steps:
    - run:
        command: echo Running job b
    - run:
        command: cat path_b/README.md
    executor: go
workflows:
  job-workflow:
    jobs:
    - job_a
    - job_b
