version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md
  job_c:
    executor: base
    steps:
      - checkout
      - run: echo "running job c"
      - run: cat path_b/README.md

job_a: &job_a
  name: job_a

job_b: &job_b
  name: job_b
  requires:
    - job_a

job_c: &job_c
  name: job_c
  requires:
    - job_a

workflows:
  workflow:
    jobs:
      - job_a:
          <<: *job_a
      - job_b: 
          <<: *job_b
      - job_c:
          <<: *job_c