version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  macos:
    macos:
      xcode: 13.4.1
    resource_class: large

jobs:
  macos:
    executor: macos
    parallelism: 2
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md

workflows:
  workflow-a:
    jobs:
      - macos