version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo $CIRCLE_PULL_REQUEST

workflows:
  workflow-a:
    jobs:
      - job_a