version: 2.1

setup: true

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md

workflows:
  workflow-a:
    jobs:
      - job_a
