version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

name-anchor-a: &name-anchor-a
  name: anchor-named-job-a
name-anchor-b: &name-anchor-b
  name: anchor-named-job-b

workflows:
  workflow:
    jobs:
      - job_a:
          <<: *name-anchor-a
      - job_b: 
          <<: *name-anchor-b