version: 2.1

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  job1:
    executor: custom-node
    steps:
      - 'run: echo "The tests have started"'
      - run: echo "tests complete let's send the complete status" || true
      - run:
          name: start job2
          command: |
            curl -u ${CIRCLECI_TOKEN}: \
            -d build_parameters[CIRCLE_JOB]=job2 \
            https://circleci.com/api/v1.1/project/github/felixshiftellecon/circleci-playground/tree/$CIRCLE_BRANCH
      - run: |
              echo "I am caching while the other jobs runs hopefully"
              sleep 20
              echo "Done caching!"
  job2:
    executor: custom-node
    steps:
      - run: echo "I should run before the caching is complete"



workflows:
  version: 2
  job-workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
