version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

commands:
      run_and_log:
        parameters:
          cmd:
            type: string
        steps:
          - run:
              command: |
                set -x
                mkdir -p /tmp/logs/
                echo "<< parameters.cmd >>" | tee -a /tmp/logs/build_output.txt
                eval "<< parameters.cmd >>" | tee -a /tmp/logs/build_output.txt
      store_build_logs:
        steps:
          - run: cat /tmp/logs/build_output.txt
          - store_artifacts:
              path: /tmp/logs/build_output.txt

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run_and_log:
          cmd: echo "Running job a"
      - run_and_log:
          cmd: cat path_a/README.md
      - store_build_logs
workflows:
  workflow-a:
    jobs:
      - job_a