version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: echo "I'm in the middle"

workflows:
  workflow-a:
    jobs:
      - job_a:
          pre-steps:
            - run:
                command: echo "I'm from a pre step" >> prestep.txt
          post-steps:
            - run:
                command: cat prestep.txt