version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  test:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - aws-cli/setup
      - run: |
          echo 'export CODEPUSH_DEPLOYMENT_NAME=pr${CIRCLE_PULL_REQUEST##*/}' >> "$BASH_ENV"
          echo "$CODEPUSH_DEPLOYMENT_NAME"
      - run: |
          echo "$CODEPUSH_DEPLOYMENT_NAME"
workflows:
  setup-workflow:
    jobs:
      - test