version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:latest
    steps:
      - run: |
          echo "export CODEPUSH_DEPLOYMENT_NAME=pr${CIRCLE_PULL_REQUEST##*/}" >> "$BASH_ENV"
          echo $CODEPUSH_DEPLOYMENT_NAME

workflows:
  setup-workflow:
    jobs:
      - test