version: 2.1

jobs:
  get-uuid-and-username:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
          user_UUID=$(curl --request GET \
          --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID \
          --header 'Circle-Token: $CIRCLECI_TOKEN' | jq '.started_by')
          
          echo $user_UUID
          echo $CIRCLE_USERNAME

workflows:
  version: 2
  get-uuid-and-username:
    jobs:
      - get-uuid-and-username