version: 2.1

jobs:
  kaniko:
    docker:
      - image: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ""
    steps:
      - checkout
      - run:
          name: Building-a-container
          command: |
            /kaniko/executor \
                --context "$(pwd)" \
                --dockerfile "$(pwd)/Dockerfile" \
                --no-push

workflows:
  kaniko:
    jobs:
      - kaniko