version: 2.1

executors:
  apple-large:
    macos:
        xcode: "14.2.0"
    resource_class: macos.m1.large.gen1
    
jobs:
  job_a:
    executor: apple-large
    steps:
      - run: echo "Running job a"

workflows:
  workflow-a:
    jobs:
      - job_a