version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: |
              echo "${CIRCLE_PULL_REQUEST##*/}
      - run: echo $PR_number

workflows:
  workflow-a:
    jobs:
      - job_a