version: 2.1

setup: true

orbs:
  continuation: circleci/circleci-cli@0.1.9

jobs:
  job_a:
    executor: circleci-cli/default
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md

workflows:
  testing:
    jobs:
      - job_a