version: 2.1

jobs:
  buildah:
    docker:
     - image: quay.io/buildah/stable:v1.31.2
    steps:
      - checkout
      - run:
          name: sanity-test
          command: |
            buildah version
      - run:
          name: Building-a-container
          command: |
            buildah bud -f ./Dockerfile -t hello-world-test:0.1

workflows:
  buildah:
    jobs:
      - buildah