version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

commands:
      enable_logging:
        steps:
          - run:
              command: |
                set -x
                echo 'set -x' >> $BASH_ENV
                mkdir -p /tmp/logs/
                exec > >(tee -a /tmp/logs/build_output.txt)
                echo 'mkdir -p /tmp/logs/' >> $BASH_ENV
                echo 'exec > >(tee -a /tmp/logs/build_output.txt)' >> $BASH_ENV
      store_build_logs:
        steps:
          - run: cat /tmp/logs/build_output.txt
          - store_artifacts:
              path: /tmp/logs/build_output.txt

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md
      - run: cat /tmp/logs/build_output.txt
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

workflows:
  workflow-a:
    jobs:
      - job_a:
          pre-steps:
            - enable_logging
          post-steps:
            - store_build_logs
      - job_b:
          pre-steps:
            - enable_logging
          post-steps:
            - store_build_logs