version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    parameters:
      hello:
        type: string
        default: "hello"
      names:
        type: string
        default: "John"
    steps:
      - run: echo "<< parameters.hello >> << parameters.names >>"

workflows:
  workflow-a:
    jobs:
      - job_a:
          name: "<< matrix.hello >> << matrix.names >>"
          matrix:
            parameters:
              hello:
                - "hello"
              names:
                - "john"