version: 2.1

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  macos:
    macos:
      xcode: 14.0.1
    resource_class: macos.x86.medium.gen2

jobs:
  macos:
    executor: macos
    steps:
      - checkout
      - run: df -h
      - run: xcversion install 12.5

workflows:
  workflow-a:
    jobs:
      - macos