version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.0
  continuation: circleci/continuation@0.2.0

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  determine-workflow:
    executor: base
    steps:
      - checkout
      - path-filtering/set-parameters:
          mapping: |
            .* no-workflow true
            path_*/ yes-workflow true
          output-path: /tmp/pipeline-parameters.json
      - run:
          name: Check if utility file was changed and stop workflow
          command: |
            # Pull parameters set in the previous step into bash
            eval $(jq -r 'to_entries | .[] | "export \(.key)=\(.value)"' /tmp/pipeline-parameters.json)

            # Continue job or halt based on parameters set above
            if [  "$no-workflow" = "true" ] && [ "$yes-workflow" = "true" ]; then
              echo "Commit has both utility and code changes, starting the next workflow"
            elseif [ "$no-workflow" = "true" ]; then
                circleci-agent step halt
            else
              echo "Commit has code changes, starting the next workflow"
            fi
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          parameters: /tmp/pipeline-parameters.json



workflows:
  setup-workflow:
    jobs:
      - determine-workflow