version: 2.1

jobs:
  kaniko:
    docker:
      - image: gcr.io/kaniko-project/executor:debug
    steps:
      - checkout
      - run:
          name: Building-a-container
          command: |
            /kaniko/executor \
                --context "$(pwd)" \
                --dockerfile "$(pwd)/Dockerfile"

workflows:
  kaniko:
    jobs:
      - kaniko