version: 2.1

jobs:
  workflow-changing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Working directory change via step env var
          environment:
            CIRCLE_WORKING_DIRECTORY: ~/testing
          command: echo $CIRCLE_WORKING_DIRECTORY
      - run:
          name: Working directory back to normal
          command: echo $CIRCLE_WORKING_DIRECTORY
      - run:
          name: Working directory change via bash env
          command: echo 'export CIRCLE_WORKING_DIRECTORY=~/testingtwo' >> $BASH_ENV
      - run:
          name: Working directory matches previous step
          command: echo $CIRCLE_WORKING_DIRECTORY




workflows:
  version: 2
  workflow-changing:
    jobs:
      - workflow-changing
