version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  set-params-and-continue:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            matches: { pattern: "^hotfix-.*", value: << pipeline.git.branch >> }
          steps:
            - run: |
                jq -n '. + {"executor_being_used": "big_boy"}' > /tmp/pipeline-parameters.json
      - when:
          condition:
            not:
              matches: { pattern: "^hotfix-.*", value: << pipeline.git.branch >> }
          steps:
            - run: |
                jq -n '. + {"executor_being_used": "small_boy"}' > /tmp/pipeline-parameters.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json

workflows:
  setup-workflow:
    jobs:
      - set-params-and-continue