version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
  macos:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.large.gen1
    
jobs:
  job_a:
    executor: macos
    steps:
      - run: echo "Running job a"
      - run: cat path_a/README.md

workflows:
  workflow-a:
    jobs:
      - job_a