version: 2.1

orbs:
  orb-test: felixshiftellecon/orb-test@1.0.0

parameters:
  run-path-a:
    type: boolean
    default: false
  run-path-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  setup:
    executor: base
    steps:
      - run: echo "Running setup"
  job_a:
    executor: base
    parameters:
      env:
       type: string
       default: "dev"
    steps:
      - run: echo "Running job <<parameters.env>>"
  job_b:
    executor: base
    parameters:
      env:
       type: enum
       enum: ["dev", "test"]
    steps:
      - run: echo "running job b"
  job_c:
    executor: base
    parameters:
      env:
       type: enum
       enum: ["dev", "test"]
    steps:
      - run: echo "running job c"

job_a: &job_a
  name: job_a
  requires:
    - setup

job_b: &job_b
  name: job_b
  requires:
    - orb-test/hello

job_c: &job_c
  requires:
    - job_a
    - setup

workflows:
  workflow:
    jobs:
      - setup
      - orb-test/hello:
          to: John
      - job_b:
          env: test 
          <<: *job_b
      - job_c:
          env: test
          <<: *job_c
  workflow-2:
    jobs:
      - setup
      - orb-test/hello:
          to: Will
      - job_b:
          env: dev 
          <<: *job_b
      - job_c:
          env: dev
          <<: *job_c