version: 2.1

orbs:
  cat-orb:
    commands:
      cat_file:
        parameters:
          file_path:
            default: path_a/README.md
        steps:
          - run: cat << parameters.file_path >>

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo "Running job a"
      - cat-orb/cat_file
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - cat-orb/cat_file
          file_path: path_b/README.md

workflows:
  workflow-a:
    jobs:
      - job_a
      - job_b