version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: echo "export PR_number=${CIRCLE_PULL_REQUEST##*/}" >> "BASH_ENV"
      - run: echo $PR_number

workflows:
  workflow-a:
    jobs:
      - job_a