version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    resource_class: small
    steps:
      - checkout

      - ruby/install:
          version: '3'
      
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build