version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
      working_directory: /path_a

jobs:
  job_a:
    executor: base
    steps:
      - run: rm -r /path_a
      - checkout
      - run: echo "Running job a"

workflows:
  workflow-a:
    jobs:
      - job_a