version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@2.1.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo $hello_env_var
      - run: echo $CIRCLE_OIDC_TOKEN >> oidc-test.txt
      - run: cat oidc-test.txt
  job_b:
    resource_class: $large_resource_class
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: aws sts assume-role-with-web-identity --role-arn "arn:aws:iam::660990364978:role/BasicEng" --role-session-name Nick-S-test --web-identity-token $CIRCLE_OIDC_TOKEN

workflows:
  job-workflow:
    jobs:
      - job_a:
          context:
            - hello-context
      - job_b:
          context:
            -hello-context
