version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - run: |
              mkdir tmp/workspace/
              echo "export test='testing'" >> tmp/workspace/new_env_vars
              echo "export PR_number=${CIRCLE_PULL_REQUEST##*/}" >> tmp/workspace/new_env_vars
      - run: |
              cat tmp/workspace/new_env_vars >> "$BASH_ENV"
              source "$BASH_ENV"
              echo $PR_number
              echo $test
      - persist_to_workspace:
          root: tmp/workspace/
          paths: new_env_vars
  job_b:
    executor: base
    steps:
      - attach_workspace:
          at: tmp/workspace/
      - run: |
              cat tmp/workspace/new_env_vars >> "$BASH_ENV"
              source "$BASH_ENV"
              echo $PR_number
              echo $test


workflows:
  workflow-a:
    jobs:
      - job_a
      - job_b:
          requires:
            - job_a