version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    parameters:
      version:
        type: string
      os:
        type: string
    executor: base
    steps:
      - checkout
      - run: echo "Running job a with matrix << parameters.version >>--<< parameters.os >>"
  job_b:
    parameters:
      version:
        type: string
      os:
        type: string
    executor: base
    steps:
      - checkout
      - run: echo "running job b with matrix << parameters.version >>--<< parameters.os >>"

workflows:
  workflow:
    jobs:
      - job_a:
          name: job-a-v-<< matrix.version >>-<< matrix.os >>
          matrix:
            parameters:
              version: ["first", "second", "third"]
              os: ["macos", "windows", "linux"]
      - hold:
          name: the approval
          type: approval
          requires:
           - job-a-v-first-macos
           - job-a-v-first-windows
           - job-a-v-first-linux
           - job-a-v-second-macos
           - job-a-v-second-windows
           - job-a-v-second-linux
           - job-a-v-third-macos
           - job-a-v-third-windows
           - job-a-v-third-linux
      - job_b:
          name: job-b-v-<< matrix.version >>-<< matrix.os >>
          matrix:
            parameters:
              version: ["first", "second", "third"]
              os: ["macos", "windows", "linux"]
          requires:
            - the approval
