version: 2.1

executors:
  medium:
    macos:
      xcode: 14.2.0
    resource_class: medium
  medium_gen2:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
  large:
    macos:
      xcode: 14.2.0
    resource_class: large
  large_gen1:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1

jobs:
  job_a:
    parameters:
      mac_executor:
        type: executor
    executor: << parameters.mac_executor >>
    steps:
      - run: df -H

workflows:
  macos-disk-size:
    jobs:
      - job_a:
          matrix:
            parameters:
              mac_executor: [ medium, medium_gen2, large, large_gen1, ]