version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    resource_class: small
    steps:
      - checkout
      - run:
          name: I'm a failure
          command: touch background_status.txt # || exit 1
          background: true
      - run: echo "Running job a"
      - run: 
          name: Background Step Failed
          command: "[ -f background_status.txt ]"

workflows:
  workflow-a:
    jobs:
      - job_a