version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo $hello_env_var
      - run: echo $CIRCLE_OIDC_TOKEN
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo "running job b"
      - run: cat path_b/README.md

workflows:
  job-workflow:
    jobs:
      - job_a:
          context:
            - hello-context
      - job_b
