version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0

executors:
  base:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: large

jobs:
  build-deploy:
    executor: base
    environment:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ROLE_ARN: arn:aws:iam::660990364978:role/BasicEng
      ECR_REPO: 660990364978.dkr.ecr.us-east-2.amazonaws.com
    steps:
      - checkout
      - aws-cli/install
      - run: docker build -t nicks-testing .
      - run: aws sts assume-role-with-web-identity --role-arn "$AWS_ROLE_ARN" --role-session-name Nick-S-test --web-identity-token $CIRCLE_OIDC_TOKEN
      - run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - run: docker tag nicks-testing:latest $ECR_REPO/nicks-testing:latest
      - run: docker push $ECR_REPO/nicks-testing:latest

workflows:
  job-workflow:
    jobs:
      - build-deploy:
          context: hello-context
