version: 2.1

orbs:
  vault: awesomecicd/vault@0.0.2

jobs:
  job_a:
    docker:
      image: cimg/base@latest
    steps:
      - checkout
      - vault/load-credentials
workflows:
  workflow-a:
    jobs:
      - job_a