version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  job_a:
    executor: win/default
    steps:
      - run: setx TEST "testing"
      - run: echo $TEST

workflows:
  workflow-a:
    jobs:
      - job_a