version: 2.1

parameters:
  infrastructure-required:
    type: boolean
    default: false
  destroy-infrastructure:
    type: boolean
    default: false
  environment:
    type: string
    default: "dev"
  testing-required:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  setup_terraform:
    executor: base
    steps:
      - run: echo "setting up terraform"
  deploy_terraform:
    executor: base
    parameters:
      service:
        description: "Service to spin up"
        type: string
        default: "s3"
    steps:
      - run: echo "deploying terraform service << parameters.service >>"
  destroy_terraform:
    executor: base
    steps:
      - run: echo "destroy terraform infrastructure"
  tests_or_something:
    executor: base
    steps:
      - run: echo "use << pipeline.parameters.environment >>"

workflows:
  deploy_infrastructure:
    when: << pipeline.parameters.infrastructure-required >>
    jobs:
      - setup_terraform
      - deploy_s3_hold:
          type: approval
          requires:
            - setup_terraform
      - deploy_terraform:
          name: Deploy s3
          service: s3
          requires:
            - hold
      - deploy_ec2_hold:
          type: approval
          requires:
            - setup_terraform
      - deploy_terraform:
          name: Deploy ec2
          service: ec2
          requires:
            - hold
  testing_something:
    when: << pipeline.parameters.testing-required >>
    jobs:
      - tests_or_something
  destroy_infrastructure:
    when: << pipeline.parameters.destroy-infrastructure >>
    jobs:
      - destroy_terraform