version: 2.1

parameters:
  executor_being_used:
    type: string
    default: "small_boy"

executors:
  small_boy:
    macos:
      xcode: "15.4.0"
    resource_class: m2pro.medium
  big_boy:
    macos:
      xcode: "15.4.0"
    resource_class: m2pro.medium


jobs:
  job_a:
    parameters:
      the_executor:
        type: executor
        default: small_boy
    executor: << parameters.the_executor >>
    steps:
      - checkout
      - run: echo "Running job a"
      - run: cat path_a/README.md

workflows:
  workflow-a:
    jobs:
      - job_a:
          the_executor: << pipeline.parameters.executor_being_used >>