version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  continue_job:
    executor: custom-node
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/config.yml



workflows:
  jobs:
    continue:
    - continue_job
