version: 2.1

setup: true

orbs: circleci/continuation

executors:
  custom-node:
    docker:
      - image: circleci/node

jobs:
  continue_job:
    executor: custom-node
    steps:
      - continuation/continue:
          configuration_path: ./config.yml



workflows:
  jobs:
    continue:
    - continue_job
